# This is the configuration file for the go-notification service.

Dispatch:
  service_name: "push-dispatch"
  log_file: "push-dispatch.log"
  ip: "0.0.0.0"
  internal_ip: "0.0.0.0"
  port: 30001
  heart_beat_internal: 30

Logic:
  service_name: "push-logic.n1"
  log_file: "push-logic.log"
  worker_num: 2

HttpRequestAPI: "http://192.168.16.222/hero/1.0/cn/api/push.php"

Etcd:
  dial_timeout: 5
  request_timeout: 10
  end_points: ["localhost:2379"]
  username: ""
  password: ""

Redis:
  - ["192.168.16.222", "4100", ""]
